/*
 * This file is generated by jOOQ.
*/
package micropost.data.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import micropost.data.tables.Micropost;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MicropostRecord extends UpdatableRecordImpl<MicropostRecord> implements Record4<Integer, String, String, OffsetDateTime> {

    private static final long serialVersionUID = 1985548729;

    /**
     * Setter for <code>public.micropost.post_id</code>.
     */
    public MicropostRecord setPostId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.micropost.post_id</code>.
     */
    public Integer getPostId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.micropost.user_nickname</code>.
     */
    public MicropostRecord setUserNickname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.micropost.user_nickname</code>.
     */
    public String getUserNickname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.micropost.content</code>.
     */
    public MicropostRecord setContent(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.micropost.content</code>.
     */
    public String getContent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.micropost.created_at</code>.
     */
    public MicropostRecord setCreatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.micropost.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, OffsetDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, OffsetDateTime> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Micropost.MICROPOST.POST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Micropost.MICROPOST.USER_NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Micropost.MICROPOST.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field4() {
        return Micropost.MICROPOST.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPostId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicropostRecord value1(Integer value) {
        setPostId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicropostRecord value2(String value) {
        setUserNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicropostRecord value3(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicropostRecord value4(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MicropostRecord values(Integer value1, String value2, String value3, OffsetDateTime value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MicropostRecord
     */
    public MicropostRecord() {
        super(Micropost.MICROPOST);
    }

    /**
     * Create a detached, initialised MicropostRecord
     */
    public MicropostRecord(Integer postId, String userNickname, String content, OffsetDateTime createdAt) {
        super(Micropost.MICROPOST);

        set(0, postId);
        set(1, userNickname);
        set(2, content);
        set(3, createdAt);
    }
}
