/*
 * This file is generated by jOOQ.
*/
package micropost.data.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Micropost implements Serializable {

    private static final long serialVersionUID = 990462167;

    private final Integer        id;
    private final String         content;
    private final OffsetDateTime createdAt;
    private final String         userId;

    public Micropost(Micropost value) {
        this.id = value.id;
        this.content = value.content;
        this.createdAt = value.createdAt;
        this.userId = value.userId;
    }

    public Micropost(
        Integer        id,
        String         content,
        OffsetDateTime createdAt,
        String         userId
    ) {
        this.id = id;
        this.content = content;
        this.createdAt = createdAt;
        this.userId = userId;
    }

    public Integer getId() {
        return this.id;
    }

    public String getContent() {
        return this.content;
    }

    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    public String getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Micropost (");

        sb.append(id);
        sb.append(", ").append(content);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
