/*
 * This file is generated by jOOQ.
*/
package micropost.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostStatistics implements Serializable {

    private static final long serialVersionUID = 1630451305;

    private final Integer id;
    private final Integer words;
    private final Object  wordCounts;
    private final Integer postId;

    public PostStatistics(PostStatistics value) {
        this.id = value.id;
        this.words = value.words;
        this.wordCounts = value.wordCounts;
        this.postId = value.postId;
    }

    public PostStatistics(
        Integer id,
        Integer words,
        Object  wordCounts,
        Integer postId
    ) {
        this.id = id;
        this.words = words;
        this.wordCounts = wordCounts;
        this.postId = postId;
    }

    public Integer getId() {
        return this.id;
    }

    public Integer getWords() {
        return this.words;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getWordCounts() {
        return this.wordCounts;
    }

    public Integer getPostId() {
        return this.postId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PostStatistics (");

        sb.append(id);
        sb.append(", ").append(words);
        sb.append(", ").append(wordCounts);
        sb.append(", ").append(postId);

        sb.append(")");
        return sb.toString();
    }
}
