/*
 * This file is generated by jOOQ.
*/
package micropost.data.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostStatistics implements Serializable {

    private static final long serialVersionUID = -884775165;

    private final Integer postId;
    private final Integer totalWords;
    private final Integer alphanumeric;
    private final Integer nonAlphanumeric;
    private final String  wordOccurrence;

    public PostStatistics(PostStatistics value) {
        this.postId = value.postId;
        this.totalWords = value.totalWords;
        this.alphanumeric = value.alphanumeric;
        this.nonAlphanumeric = value.nonAlphanumeric;
        this.wordOccurrence = value.wordOccurrence;
    }

    public PostStatistics(
        Integer postId,
        Integer totalWords,
        Integer alphanumeric,
        Integer nonAlphanumeric,
        String  wordOccurrence
    ) {
        this.postId = postId;
        this.totalWords = totalWords;
        this.alphanumeric = alphanumeric;
        this.nonAlphanumeric = nonAlphanumeric;
        this.wordOccurrence = wordOccurrence;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public Integer getTotalWords() {
        return this.totalWords;
    }

    public Integer getAlphanumeric() {
        return this.alphanumeric;
    }

    public Integer getNonAlphanumeric() {
        return this.nonAlphanumeric;
    }

    public String getWordOccurrence() {
        return this.wordOccurrence;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PostStatistics (");

        sb.append(postId);
        sb.append(", ").append(totalWords);
        sb.append(", ").append(alphanumeric);
        sb.append(", ").append(nonAlphanumeric);
        sb.append(", ").append(wordOccurrence);

        sb.append(")");
        return sb.toString();
    }
}
