// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: post_statistics.proto

package micropost.proto;

public final class PostStatistics {
  private PostStatistics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostStatisticsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PostStatisticsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 postId = 1;</code>
     */
    int getPostId();

    /**
     * <code>string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code PostStatisticsRequest}
   */
  public  static final class PostStatisticsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PostStatisticsRequest)
      PostStatisticsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostStatisticsRequest.newBuilder() to construct.
    private PostStatisticsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostStatisticsRequest() {
      postId_ = 0;
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostStatisticsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              postId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return micropost.proto.PostStatistics.internal_static_PostStatisticsRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return micropost.proto.PostStatistics.internal_static_PostStatisticsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              micropost.proto.PostStatistics.PostStatisticsRequest.class, micropost.proto.PostStatistics.PostStatisticsRequest.Builder.class);
    }

    public static final int POSTID_FIELD_NUMBER = 1;
    private int postId_;
    /**
     * <code>int32 postId = 1;</code>
     */
    public int getPostId() {
      return postId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (postId_ != 0) {
        output.writeInt32(1, postId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, postId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof micropost.proto.PostStatistics.PostStatisticsRequest)) {
        return super.equals(obj);
      }
      micropost.proto.PostStatistics.PostStatisticsRequest other = (micropost.proto.PostStatistics.PostStatisticsRequest) obj;

      boolean result = true;
      result = result && (getPostId()
          == other.getPostId());
      result = result && getContent()
          .equals(other.getContent());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + getPostId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static micropost.proto.PostStatistics.PostStatisticsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(micropost.proto.PostStatistics.PostStatisticsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PostStatisticsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PostStatisticsRequest)
        micropost.proto.PostStatistics.PostStatisticsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return micropost.proto.PostStatistics.internal_static_PostStatisticsRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return micropost.proto.PostStatistics.internal_static_PostStatisticsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                micropost.proto.PostStatistics.PostStatisticsRequest.class, micropost.proto.PostStatistics.PostStatisticsRequest.Builder.class);
      }

      // Construct using micropost.proto.PostStatistics.PostStatisticsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        postId_ = 0;

        content_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return micropost.proto.PostStatistics.internal_static_PostStatisticsRequest_descriptor;
      }

      public micropost.proto.PostStatistics.PostStatisticsRequest getDefaultInstanceForType() {
        return micropost.proto.PostStatistics.PostStatisticsRequest.getDefaultInstance();
      }

      public micropost.proto.PostStatistics.PostStatisticsRequest build() {
        micropost.proto.PostStatistics.PostStatisticsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public micropost.proto.PostStatistics.PostStatisticsRequest buildPartial() {
        micropost.proto.PostStatistics.PostStatisticsRequest result = new micropost.proto.PostStatistics.PostStatisticsRequest(this);
        result.postId_ = postId_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof micropost.proto.PostStatistics.PostStatisticsRequest) {
          return mergeFrom((micropost.proto.PostStatistics.PostStatisticsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(micropost.proto.PostStatistics.PostStatisticsRequest other) {
        if (other == micropost.proto.PostStatistics.PostStatisticsRequest.getDefaultInstance()) return this;
        if (other.getPostId() != 0) {
          setPostId(other.getPostId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        micropost.proto.PostStatistics.PostStatisticsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (micropost.proto.PostStatistics.PostStatisticsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int postId_ ;
      /**
       * <code>int32 postId = 1;</code>
       */
      public int getPostId() {
        return postId_;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder setPostId(int value) {
        
        postId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder clearPostId() {
        
        postId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PostStatisticsRequest)
    }

    // @@protoc_insertion_point(class_scope:PostStatisticsRequest)
    private static final micropost.proto.PostStatistics.PostStatisticsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new micropost.proto.PostStatistics.PostStatisticsRequest();
    }

    public static micropost.proto.PostStatistics.PostStatisticsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostStatisticsRequest>
        PARSER = new com.google.protobuf.AbstractParser<PostStatisticsRequest>() {
      public PostStatisticsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostStatisticsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostStatisticsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostStatisticsRequest> getParserForType() {
      return PARSER;
    }

    public micropost.proto.PostStatistics.PostStatisticsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostStatisticsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PostStatisticsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 postId = 1;</code>
     */
    int getPostId();

    /**
     * <code>int32 alphanumeric = 2;</code>
     */
    int getAlphanumeric();

    /**
     * <code>int32 nonAlphanumeric = 3;</code>
     */
    int getNonAlphanumeric();

    /**
     * <code>int32 totalWords = 4;</code>
     */
    int getTotalWords();

    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */
    int getWordOccurrenceCount();
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */
    boolean containsWordOccurrence(
        java.lang.String key);
    /**
     * Use {@link #getWordOccurrenceMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getWordOccurrence();
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getWordOccurrenceMap();
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */

    int getWordOccurrenceOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */

    int getWordOccurrenceOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code PostStatisticsResponse}
   */
  public  static final class PostStatisticsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PostStatisticsResponse)
      PostStatisticsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostStatisticsResponse.newBuilder() to construct.
    private PostStatisticsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostStatisticsResponse() {
      postId_ = 0;
      alphanumeric_ = 0;
      nonAlphanumeric_ = 0;
      totalWords_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostStatisticsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              postId_ = input.readInt32();
              break;
            }
            case 16: {

              alphanumeric_ = input.readInt32();
              break;
            }
            case 24: {

              nonAlphanumeric_ = input.readInt32();
              break;
            }
            case 32: {

              totalWords_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                wordOccurrence_ = com.google.protobuf.MapField.newMapField(
                    WordOccurrenceDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              wordOccurrence__ = input.readMessage(
                  WordOccurrenceDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              wordOccurrence_.getMutableMap().put(
                  wordOccurrence__.getKey(), wordOccurrence__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return micropost.proto.PostStatistics.internal_static_PostStatisticsResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetWordOccurrence();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return micropost.proto.PostStatistics.internal_static_PostStatisticsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              micropost.proto.PostStatistics.PostStatisticsResponse.class, micropost.proto.PostStatistics.PostStatisticsResponse.Builder.class);
    }

    private int bitField0_;
    public static final int POSTID_FIELD_NUMBER = 1;
    private int postId_;
    /**
     * <code>int32 postId = 1;</code>
     */
    public int getPostId() {
      return postId_;
    }

    public static final int ALPHANUMERIC_FIELD_NUMBER = 2;
    private int alphanumeric_;
    /**
     * <code>int32 alphanumeric = 2;</code>
     */
    public int getAlphanumeric() {
      return alphanumeric_;
    }

    public static final int NONALPHANUMERIC_FIELD_NUMBER = 3;
    private int nonAlphanumeric_;
    /**
     * <code>int32 nonAlphanumeric = 3;</code>
     */
    public int getNonAlphanumeric() {
      return nonAlphanumeric_;
    }

    public static final int TOTALWORDS_FIELD_NUMBER = 4;
    private int totalWords_;
    /**
     * <code>int32 totalWords = 4;</code>
     */
    public int getTotalWords() {
      return totalWords_;
    }

    public static final int WORDOCCURRENCE_FIELD_NUMBER = 5;
    private static final class WordOccurrenceDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  micropost.proto.PostStatistics.internal_static_PostStatisticsResponse_WordOccurrenceEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> wordOccurrence_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetWordOccurrence() {
      if (wordOccurrence_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            WordOccurrenceDefaultEntryHolder.defaultEntry);
      }
      return wordOccurrence_;
    }

    public int getWordOccurrenceCount() {
      return internalGetWordOccurrence().getMap().size();
    }
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */

    public boolean containsWordOccurrence(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetWordOccurrence().getMap().containsKey(key);
    }
    /**
     * Use {@link #getWordOccurrenceMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getWordOccurrence() {
      return getWordOccurrenceMap();
    }
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getWordOccurrenceMap() {
      return internalGetWordOccurrence().getMap();
    }
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */

    public int getWordOccurrenceOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetWordOccurrence().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
     */

    public int getWordOccurrenceOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetWordOccurrence().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (postId_ != 0) {
        output.writeInt32(1, postId_);
      }
      if (alphanumeric_ != 0) {
        output.writeInt32(2, alphanumeric_);
      }
      if (nonAlphanumeric_ != 0) {
        output.writeInt32(3, nonAlphanumeric_);
      }
      if (totalWords_ != 0) {
        output.writeInt32(4, totalWords_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetWordOccurrence(),
          WordOccurrenceDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (postId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, postId_);
      }
      if (alphanumeric_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, alphanumeric_);
      }
      if (nonAlphanumeric_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, nonAlphanumeric_);
      }
      if (totalWords_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalWords_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetWordOccurrence().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        wordOccurrence__ = WordOccurrenceDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, wordOccurrence__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof micropost.proto.PostStatistics.PostStatisticsResponse)) {
        return super.equals(obj);
      }
      micropost.proto.PostStatistics.PostStatisticsResponse other = (micropost.proto.PostStatistics.PostStatisticsResponse) obj;

      boolean result = true;
      result = result && (getPostId()
          == other.getPostId());
      result = result && (getAlphanumeric()
          == other.getAlphanumeric());
      result = result && (getNonAlphanumeric()
          == other.getNonAlphanumeric());
      result = result && (getTotalWords()
          == other.getTotalWords());
      result = result && internalGetWordOccurrence().equals(
          other.internalGetWordOccurrence());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POSTID_FIELD_NUMBER;
      hash = (53 * hash) + getPostId();
      hash = (37 * hash) + ALPHANUMERIC_FIELD_NUMBER;
      hash = (53 * hash) + getAlphanumeric();
      hash = (37 * hash) + NONALPHANUMERIC_FIELD_NUMBER;
      hash = (53 * hash) + getNonAlphanumeric();
      hash = (37 * hash) + TOTALWORDS_FIELD_NUMBER;
      hash = (53 * hash) + getTotalWords();
      if (!internalGetWordOccurrence().getMap().isEmpty()) {
        hash = (37 * hash) + WORDOCCURRENCE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetWordOccurrence().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static micropost.proto.PostStatistics.PostStatisticsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(micropost.proto.PostStatistics.PostStatisticsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PostStatisticsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PostStatisticsResponse)
        micropost.proto.PostStatistics.PostStatisticsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return micropost.proto.PostStatistics.internal_static_PostStatisticsResponse_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetWordOccurrence();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableWordOccurrence();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return micropost.proto.PostStatistics.internal_static_PostStatisticsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                micropost.proto.PostStatistics.PostStatisticsResponse.class, micropost.proto.PostStatistics.PostStatisticsResponse.Builder.class);
      }

      // Construct using micropost.proto.PostStatistics.PostStatisticsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        postId_ = 0;

        alphanumeric_ = 0;

        nonAlphanumeric_ = 0;

        totalWords_ = 0;

        internalGetMutableWordOccurrence().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return micropost.proto.PostStatistics.internal_static_PostStatisticsResponse_descriptor;
      }

      public micropost.proto.PostStatistics.PostStatisticsResponse getDefaultInstanceForType() {
        return micropost.proto.PostStatistics.PostStatisticsResponse.getDefaultInstance();
      }

      public micropost.proto.PostStatistics.PostStatisticsResponse build() {
        micropost.proto.PostStatistics.PostStatisticsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public micropost.proto.PostStatistics.PostStatisticsResponse buildPartial() {
        micropost.proto.PostStatistics.PostStatisticsResponse result = new micropost.proto.PostStatistics.PostStatisticsResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.postId_ = postId_;
        result.alphanumeric_ = alphanumeric_;
        result.nonAlphanumeric_ = nonAlphanumeric_;
        result.totalWords_ = totalWords_;
        result.wordOccurrence_ = internalGetWordOccurrence();
        result.wordOccurrence_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof micropost.proto.PostStatistics.PostStatisticsResponse) {
          return mergeFrom((micropost.proto.PostStatistics.PostStatisticsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(micropost.proto.PostStatistics.PostStatisticsResponse other) {
        if (other == micropost.proto.PostStatistics.PostStatisticsResponse.getDefaultInstance()) return this;
        if (other.getPostId() != 0) {
          setPostId(other.getPostId());
        }
        if (other.getAlphanumeric() != 0) {
          setAlphanumeric(other.getAlphanumeric());
        }
        if (other.getNonAlphanumeric() != 0) {
          setNonAlphanumeric(other.getNonAlphanumeric());
        }
        if (other.getTotalWords() != 0) {
          setTotalWords(other.getTotalWords());
        }
        internalGetMutableWordOccurrence().mergeFrom(
            other.internalGetWordOccurrence());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        micropost.proto.PostStatistics.PostStatisticsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (micropost.proto.PostStatistics.PostStatisticsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int postId_ ;
      /**
       * <code>int32 postId = 1;</code>
       */
      public int getPostId() {
        return postId_;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder setPostId(int value) {
        
        postId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 postId = 1;</code>
       */
      public Builder clearPostId() {
        
        postId_ = 0;
        onChanged();
        return this;
      }

      private int alphanumeric_ ;
      /**
       * <code>int32 alphanumeric = 2;</code>
       */
      public int getAlphanumeric() {
        return alphanumeric_;
      }
      /**
       * <code>int32 alphanumeric = 2;</code>
       */
      public Builder setAlphanumeric(int value) {
        
        alphanumeric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 alphanumeric = 2;</code>
       */
      public Builder clearAlphanumeric() {
        
        alphanumeric_ = 0;
        onChanged();
        return this;
      }

      private int nonAlphanumeric_ ;
      /**
       * <code>int32 nonAlphanumeric = 3;</code>
       */
      public int getNonAlphanumeric() {
        return nonAlphanumeric_;
      }
      /**
       * <code>int32 nonAlphanumeric = 3;</code>
       */
      public Builder setNonAlphanumeric(int value) {
        
        nonAlphanumeric_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nonAlphanumeric = 3;</code>
       */
      public Builder clearNonAlphanumeric() {
        
        nonAlphanumeric_ = 0;
        onChanged();
        return this;
      }

      private int totalWords_ ;
      /**
       * <code>int32 totalWords = 4;</code>
       */
      public int getTotalWords() {
        return totalWords_;
      }
      /**
       * <code>int32 totalWords = 4;</code>
       */
      public Builder setTotalWords(int value) {
        
        totalWords_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 totalWords = 4;</code>
       */
      public Builder clearTotalWords() {
        
        totalWords_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> wordOccurrence_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetWordOccurrence() {
        if (wordOccurrence_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              WordOccurrenceDefaultEntryHolder.defaultEntry);
        }
        return wordOccurrence_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableWordOccurrence() {
        onChanged();;
        if (wordOccurrence_ == null) {
          wordOccurrence_ = com.google.protobuf.MapField.newMapField(
              WordOccurrenceDefaultEntryHolder.defaultEntry);
        }
        if (!wordOccurrence_.isMutable()) {
          wordOccurrence_ = wordOccurrence_.copy();
        }
        return wordOccurrence_;
      }

      public int getWordOccurrenceCount() {
        return internalGetWordOccurrence().getMap().size();
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */

      public boolean containsWordOccurrence(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetWordOccurrence().getMap().containsKey(key);
      }
      /**
       * Use {@link #getWordOccurrenceMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getWordOccurrence() {
        return getWordOccurrenceMap();
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getWordOccurrenceMap() {
        return internalGetWordOccurrence().getMap();
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */

      public int getWordOccurrenceOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetWordOccurrence().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */

      public int getWordOccurrenceOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetWordOccurrence().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearWordOccurrence() {
        internalGetMutableWordOccurrence().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */

      public Builder removeWordOccurrence(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableWordOccurrence().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableWordOccurrence() {
        return internalGetMutableWordOccurrence().getMutableMap();
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */
      public Builder putWordOccurrence(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableWordOccurrence().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int32&gt; wordOccurrence = 5;</code>
       */

      public Builder putAllWordOccurrence(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableWordOccurrence().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PostStatisticsResponse)
    }

    // @@protoc_insertion_point(class_scope:PostStatisticsResponse)
    private static final micropost.proto.PostStatistics.PostStatisticsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new micropost.proto.PostStatistics.PostStatisticsResponse();
    }

    public static micropost.proto.PostStatistics.PostStatisticsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostStatisticsResponse>
        PARSER = new com.google.protobuf.AbstractParser<PostStatisticsResponse>() {
      public PostStatisticsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostStatisticsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostStatisticsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostStatisticsResponse> getParserForType() {
      return PARSER;
    }

    public micropost.proto.PostStatistics.PostStatisticsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostStatisticsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostStatisticsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostStatisticsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostStatisticsResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PostStatisticsResponse_WordOccurrenceEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PostStatisticsResponse_WordOccurrenceEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025post_statistics.proto\"8\n\025PostStatistic" +
      "sRequest\022\016\n\006postId\030\001 \001(\005\022\017\n\007content\030\002 \001(" +
      "\t\"\347\001\n\026PostStatisticsResponse\022\016\n\006postId\030\001" +
      " \001(\005\022\024\n\014alphanumeric\030\002 \001(\005\022\027\n\017nonAlphanu" +
      "meric\030\003 \001(\005\022\022\n\ntotalWords\030\004 \001(\005\022C\n\016wordO" +
      "ccurrence\030\005 \003(\0132+.PostStatisticsResponse" +
      ".WordOccurrenceEntry\0325\n\023WordOccurrenceEn" +
      "try\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\0012`\n\021P" +
      "ostStatisticsRpc\022K\n\026generatePostStatisti" +
      "cs\022\026.PostStatisticsRequest\032\027.PostStatist" +
      "icsResponse\"\000B\021\n\017micropost.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PostStatisticsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PostStatisticsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostStatisticsRequest_descriptor,
        new java.lang.String[] { "PostId", "Content", });
    internal_static_PostStatisticsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PostStatisticsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostStatisticsResponse_descriptor,
        new java.lang.String[] { "PostId", "Alphanumeric", "NonAlphanumeric", "TotalWords", "WordOccurrence", });
    internal_static_PostStatisticsResponse_WordOccurrenceEntry_descriptor =
      internal_static_PostStatisticsResponse_descriptor.getNestedTypes().get(0);
    internal_static_PostStatisticsResponse_WordOccurrenceEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PostStatisticsResponse_WordOccurrenceEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
