/*
 * This file is generated by jOOQ.
*/
package micropost.data.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import micropost.data.tables.PostStatistics;
import micropost.data.tables.records.PostStatisticsRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostStatisticsDao extends DAOImpl<PostStatisticsRecord, micropost.data.tables.pojos.PostStatistics, Integer> {

    /**
     * Create a new PostStatisticsDao without any configuration
     */
    public PostStatisticsDao() {
        super(PostStatistics.POST_STATISTICS, micropost.data.tables.pojos.PostStatistics.class);
    }

    /**
     * Create a new PostStatisticsDao with an attached configuration
     */
    public PostStatisticsDao(Configuration configuration) {
        super(PostStatistics.POST_STATISTICS, micropost.data.tables.pojos.PostStatistics.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(micropost.data.tables.pojos.PostStatistics object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<micropost.data.tables.pojos.PostStatistics> fetchById(Integer... values) {
        return fetch(PostStatistics.POST_STATISTICS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public micropost.data.tables.pojos.PostStatistics fetchOneById(Integer value) {
        return fetchOne(PostStatistics.POST_STATISTICS.ID, value);
    }

    /**
     * Fetch records that have <code>words IN (values)</code>
     */
    public List<micropost.data.tables.pojos.PostStatistics> fetchByWords(Integer... values) {
        return fetch(PostStatistics.POST_STATISTICS.WORDS, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<micropost.data.tables.pojos.PostStatistics> fetchByWordCounts(Object... values) {
        return fetch(PostStatistics.POST_STATISTICS.WORD_COUNTS, values);
    }

    /**
     * Fetch records that have <code>micropost_id IN (values)</code>
     */
    public List<micropost.data.tables.pojos.PostStatistics> fetchByMicropostId(Integer... values) {
        return fetch(PostStatistics.POST_STATISTICS.MICROPOST_ID, values);
    }
}
