FROM openjdk:8u151-jdk

ARG MN_VERSION=1.0.0
ENV MN_VERSION=$MN_VERSION

RUN wget https://github.com/micronaut-projects/micronaut-core/releases/download/v$MN_VERSION/micronaut-$MN_VERSION.zip
RUN unzip micronaut-$MN_VERSION
RUN rm micronaut-$MN_VERSION.zip
RUN mkdir /project
RUN chmod -R 777 /project

ENV PATH $PATH:/micronaut-$MN_VERSION/bin
