// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post_statisistics.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostStatisticsRequest struct {
	PostId               int32    `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostStatisticsRequest) Reset()         { *m = PostStatisticsRequest{} }
func (m *PostStatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*PostStatisticsRequest) ProtoMessage()    {}
func (*PostStatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_274bf51e3fb0e78a, []int{0}
}

func (m *PostStatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostStatisticsRequest.Unmarshal(m, b)
}
func (m *PostStatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostStatisticsRequest.Marshal(b, m, deterministic)
}
func (m *PostStatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostStatisticsRequest.Merge(m, src)
}
func (m *PostStatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_PostStatisticsRequest.Size(m)
}
func (m *PostStatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostStatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostStatisticsRequest proto.InternalMessageInfo

func (m *PostStatisticsRequest) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PostStatisticsRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type PostStatisticsResponse struct {
	PostId               int32            `protobuf:"varint,1,opt,name=postId,proto3" json:"postId,omitempty"`
	Alphanumeric         int32            `protobuf:"varint,2,opt,name=alphanumeric,proto3" json:"alphanumeric,omitempty"`
	NonAlphanumeric      int32            `protobuf:"varint,3,opt,name=nonAlphanumeric,proto3" json:"nonAlphanumeric,omitempty"`
	TotalWords           int32            `protobuf:"varint,4,opt,name=totalWords,proto3" json:"totalWords,omitempty"`
	WordOccurrence       map[string]int32 `protobuf:"bytes,5,rep,name=wordOccurrence,proto3" json:"wordOccurrence,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *PostStatisticsResponse) Reset()         { *m = PostStatisticsResponse{} }
func (m *PostStatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*PostStatisticsResponse) ProtoMessage()    {}
func (*PostStatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_274bf51e3fb0e78a, []int{1}
}

func (m *PostStatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostStatisticsResponse.Unmarshal(m, b)
}
func (m *PostStatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostStatisticsResponse.Marshal(b, m, deterministic)
}
func (m *PostStatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostStatisticsResponse.Merge(m, src)
}
func (m *PostStatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_PostStatisticsResponse.Size(m)
}
func (m *PostStatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostStatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostStatisticsResponse proto.InternalMessageInfo

func (m *PostStatisticsResponse) GetPostId() int32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *PostStatisticsResponse) GetAlphanumeric() int32 {
	if m != nil {
		return m.Alphanumeric
	}
	return 0
}

func (m *PostStatisticsResponse) GetNonAlphanumeric() int32 {
	if m != nil {
		return m.NonAlphanumeric
	}
	return 0
}

func (m *PostStatisticsResponse) GetTotalWords() int32 {
	if m != nil {
		return m.TotalWords
	}
	return 0
}

func (m *PostStatisticsResponse) GetWordOccurrence() map[string]int32 {
	if m != nil {
		return m.WordOccurrence
	}
	return nil
}

func init() {
	proto.RegisterType((*PostStatisticsRequest)(nil), "PostStatisticsRequest")
	proto.RegisterType((*PostStatisticsResponse)(nil), "PostStatisticsResponse")
	proto.RegisterMapType((map[string]int32)(nil), "PostStatisticsResponse.WordOccurrenceEntry")
}

func init() { proto.RegisterFile("proto/post_statisistics.proto", fileDescriptor_274bf51e3fb0e78a) }

var fileDescriptor_274bf51e3fb0e78a = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x4d, 0x6b, 0x5a, 0x3a, 0x4a, 0x95, 0x55, 0x63, 0x28, 0x28, 0x21, 0xa7, 0x80, 0x10,
	0xa1, 0x5e, 0xc4, 0x5b, 0x05, 0x91, 0xe2, 0x41, 0xd9, 0x1e, 0x7a, 0x12, 0x59, 0x37, 0x03, 0x06,
	0xe3, 0x6e, 0xdc, 0x9d, 0x28, 0xfd, 0x63, 0xfe, 0x3e, 0xc9, 0x5a, 0xa1, 0x09, 0xe9, 0x29, 0x79,
	0x6f, 0xbe, 0x7d, 0xcc, 0x63, 0xe0, 0xac, 0x34, 0x9a, 0xf4, 0x65, 0xa9, 0x2d, 0xbd, 0x58, 0x12,
	0x94, 0xdb, 0xdc, 0x52, 0x2e, 0x6d, 0xea, 0xfc, 0x78, 0x0e, 0x27, 0x4f, 0xda, 0xd2, 0xc2, 0x4d,
	0x6a, 0x9f, 0xe3, 0x67, 0x85, 0x96, 0x58, 0x00, 0x83, 0xfa, 0xcd, 0x3c, 0x0b, 0xbd, 0xc8, 0x4b,
	0x7c, 0xbe, 0x56, 0x2c, 0x84, 0xa1, 0xd4, 0x8a, 0x50, 0x51, 0xd8, 0x8b, 0xbc, 0x64, 0xc4, 0xff,
	0x65, 0xfc, 0xd3, 0x83, 0xa0, 0x9d, 0x65, 0x4b, 0xad, 0x2c, 0x6e, 0x0d, 0x8b, 0x61, 0x5f, 0x14,
	0xe5, 0x9b, 0x50, 0xd5, 0x07, 0x9a, 0x5c, 0xba, 0x44, 0x9f, 0x37, 0x3c, 0x96, 0xc0, 0x81, 0xd2,
	0x6a, 0xb6, 0x89, 0xf5, 0x1d, 0xd6, 0xb6, 0xd9, 0x39, 0x00, 0x69, 0x12, 0xc5, 0x52, 0x9b, 0xcc,
	0x86, 0xbb, 0x0e, 0xda, 0x70, 0xd8, 0x02, 0xc6, 0xdf, 0xda, 0x64, 0x8f, 0x52, 0x56, 0xc6, 0xa0,
	0x92, 0x18, 0xfa, 0x51, 0x3f, 0xd9, 0x9b, 0x5e, 0xa4, 0xdd, 0x6b, 0xa7, 0xcb, 0x06, 0x7d, 0xa7,
	0xc8, 0xac, 0x78, 0x2b, 0x62, 0x32, 0x83, 0xa3, 0x0e, 0x8c, 0x1d, 0x42, 0xff, 0x1d, 0x57, 0xae,
	0xee, 0x88, 0xd7, 0xbf, 0xec, 0x18, 0xfc, 0x2f, 0x51, 0x54, 0xb8, 0x2e, 0xf9, 0x27, 0x6e, 0x7a,
	0xd7, 0xde, 0xf4, 0x19, 0xc6, 0xcd, 0x05, 0xd8, 0x03, 0x04, 0xf7, 0xa8, 0xd0, 0x08, 0xc2, 0xd6,
	0x24, 0x48, 0x3b, 0xcf, 0x35, 0x39, 0xdd, 0xd2, 0x21, 0xde, 0xb9, 0x1d, 0x82, 0xef, 0x6e, 0xfd,
	0x3a, 0x70, 0x9f, 0xab, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x02, 0x44, 0x9f, 0x2a, 0x13, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostStatisticsClient is the client API for PostStatistics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostStatisticsClient interface {
	GeneratePostStatistics(ctx context.Context, in *PostStatisticsRequest, opts ...grpc.CallOption) (*PostStatisticsResponse, error)
}

type postStatisticsClient struct {
	cc *grpc.ClientConn
}

func NewPostStatisticsClient(cc *grpc.ClientConn) PostStatisticsClient {
	return &postStatisticsClient{cc}
}

func (c *postStatisticsClient) GeneratePostStatistics(ctx context.Context, in *PostStatisticsRequest, opts ...grpc.CallOption) (*PostStatisticsResponse, error) {
	out := new(PostStatisticsResponse)
	err := c.cc.Invoke(ctx, "/PostStatistics/GeneratePostStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostStatisticsServer is the server API for PostStatistics service.
type PostStatisticsServer interface {
	GeneratePostStatistics(context.Context, *PostStatisticsRequest) (*PostStatisticsResponse, error)
}

func RegisterPostStatisticsServer(s *grpc.Server, srv PostStatisticsServer) {
	s.RegisterService(&_PostStatistics_serviceDesc, srv)
}

func _PostStatistics_GeneratePostStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostStatisticsServer).GeneratePostStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostStatistics/GeneratePostStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostStatisticsServer).GeneratePostStatistics(ctx, req.(*PostStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostStatistics_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PostStatistics",
	HandlerType: (*PostStatisticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePostStatistics",
			Handler:    _PostStatistics_GeneratePostStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/post_statisistics.proto",
}
