---
micronaut:
    application:
        name: micropost-service
    server:
        port: 8010
---
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/micropost}
    user: micropost
    password: pass
