statistics:
  host: ${STATISTICS_HOST:localhost}
  port: ${STATISTICS_PORT:8030}
---
micronaut:
  application:
    name: micropost-service
  server:
    port: 8010
---
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:micropost}
    username: micropost
    password: pass
