/*
 * This file is generated by jOOQ.
*/
package micropost.data;


import javax.annotation.Generated;

import micropost.data.tables.Micropost;
import micropost.data.tables.PostStatistics;
import micropost.data.tables.User;
import micropost.data.tables.records.MicropostRecord;
import micropost.data.tables.records.PostStatisticsRecord;
import micropost.data.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MicropostRecord, Integer> IDENTITY_MICROPOST = Identities0.IDENTITY_MICROPOST;
    public static final Identity<PostStatisticsRecord, Integer> IDENTITY_POST_STATISTICS = Identities0.IDENTITY_POST_STATISTICS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MicropostRecord> MICROPOST_ID = UniqueKeys0.MICROPOST_ID;
    public static final UniqueKey<PostStatisticsRecord> POST_STATISTICS_ID = UniqueKeys0.POST_STATISTICS_ID;
    public static final UniqueKey<UserRecord> USER_ID = UniqueKeys0.USER_ID;
    public static final UniqueKey<UserRecord> USER_EMAIL = UniqueKeys0.USER_EMAIL;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MicropostRecord, UserRecord> MICROPOST__MICROPOST_USER_ID_FKEY = ForeignKeys0.MICROPOST__MICROPOST_USER_ID_FKEY;
    public static final ForeignKey<PostStatisticsRecord, MicropostRecord> POST_STATISTICS__POST_STATISTICS_MICROPOST_ID_FKEY = ForeignKeys0.POST_STATISTICS__POST_STATISTICS_MICROPOST_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<MicropostRecord, Integer> IDENTITY_MICROPOST = createIdentity(Micropost.MICROPOST, Micropost.MICROPOST.ID);
        public static Identity<PostStatisticsRecord, Integer> IDENTITY_POST_STATISTICS = createIdentity(PostStatistics.POST_STATISTICS, PostStatistics.POST_STATISTICS.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MicropostRecord> MICROPOST_ID = createUniqueKey(Micropost.MICROPOST, "micropost_id", Micropost.MICROPOST.ID);
        public static final UniqueKey<PostStatisticsRecord> POST_STATISTICS_ID = createUniqueKey(PostStatistics.POST_STATISTICS, "post_statistics_id", PostStatistics.POST_STATISTICS.ID);
        public static final UniqueKey<UserRecord> USER_ID = createUniqueKey(User.USER, "user_id", User.USER.ID);
        public static final UniqueKey<UserRecord> USER_EMAIL = createUniqueKey(User.USER, "user_email", User.USER.EMAIL);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<MicropostRecord, UserRecord> MICROPOST__MICROPOST_USER_ID_FKEY = createForeignKey(micropost.data.Keys.USER_ID, Micropost.MICROPOST, "micropost__micropost_user_id_fkey", Micropost.MICROPOST.USER_ID);
        public static final ForeignKey<PostStatisticsRecord, MicropostRecord> POST_STATISTICS__POST_STATISTICS_MICROPOST_ID_FKEY = createForeignKey(micropost.data.Keys.MICROPOST_ID, PostStatistics.POST_STATISTICS, "post_statistics__post_statistics_micropost_id_fkey", PostStatistics.POST_STATISTICS.MICROPOST_ID);
    }
}
