/*
 * This file is generated by jOOQ.
*/
package micropost.data;


import javax.annotation.Generated;

import micropost.data.tables.Micropost;
import micropost.data.tables.PostStatistics;
import micropost.data.tables.User;
import micropost.data.tables.records.MicropostRecord;
import micropost.data.tables.records.PostStatisticsRecord;
import micropost.data.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<MicropostRecord, Integer> IDENTITY_MICROPOST = Identities0.IDENTITY_MICROPOST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MicropostRecord> MICROPOST_ID = UniqueKeys0.MICROPOST_ID;
    public static final UniqueKey<PostStatisticsRecord> POST_STATISTICS_POST_ID_KEY = UniqueKeys0.POST_STATISTICS_POST_ID_KEY;
    public static final UniqueKey<UserRecord> USER_NICKNAME = UniqueKeys0.USER_NICKNAME;
    public static final UniqueKey<UserRecord> USER_EMAIL = UniqueKeys0.USER_EMAIL;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MicropostRecord, UserRecord> MICROPOST__MICROPOST_USER_NICKNAME_FKEY = ForeignKeys0.MICROPOST__MICROPOST_USER_NICKNAME_FKEY;
    public static final ForeignKey<PostStatisticsRecord, MicropostRecord> POST_STATISTICS__POST_STATISTICS_POST_ID_FKEY = ForeignKeys0.POST_STATISTICS__POST_STATISTICS_POST_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<MicropostRecord, Integer> IDENTITY_MICROPOST = createIdentity(Micropost.MICROPOST, Micropost.MICROPOST.POST_ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MicropostRecord> MICROPOST_ID = createUniqueKey(Micropost.MICROPOST, "micropost_id", Micropost.MICROPOST.POST_ID);
        public static final UniqueKey<PostStatisticsRecord> POST_STATISTICS_POST_ID_KEY = createUniqueKey(PostStatistics.POST_STATISTICS, "post_statistics_post_id_key", PostStatistics.POST_STATISTICS.POST_ID);
        public static final UniqueKey<UserRecord> USER_NICKNAME = createUniqueKey(User.USER, "user_nickname", User.USER.NICKNAME);
        public static final UniqueKey<UserRecord> USER_EMAIL = createUniqueKey(User.USER, "user_email", User.USER.EMAIL);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<MicropostRecord, UserRecord> MICROPOST__MICROPOST_USER_NICKNAME_FKEY = createForeignKey(micropost.data.Keys.USER_NICKNAME, Micropost.MICROPOST, "micropost__micropost_user_nickname_fkey", Micropost.MICROPOST.USER_NICKNAME);
        public static final ForeignKey<PostStatisticsRecord, MicropostRecord> POST_STATISTICS__POST_STATISTICS_POST_ID_FKEY = createForeignKey(micropost.data.Keys.MICROPOST_ID, PostStatistics.POST_STATISTICS, "post_statistics__post_statistics_post_id_fkey", PostStatistics.POST_STATISTICS.POST_ID);
    }
}
