/*
 * This file is generated by jOOQ.
*/
package micropost.data;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.micropost_id_seq</code>
     */
    public static final Sequence<Long> MICROPOST_ID_SEQ = new SequenceImpl<Long>("micropost_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.post_statistics_id_seq</code>
     */
    public static final Sequence<Long> POST_STATISTICS_ID_SEQ = new SequenceImpl<Long>("post_statistics_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
