/*
 * This file is generated by jOOQ.
*/
package micropost.data;


import javax.annotation.Generated;

import micropost.data.tables.Micropost;
import micropost.data.tables.PostStatistics;
import micropost.data.tables.User;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.micropost</code>.
     */
    public static final Micropost MICROPOST = micropost.data.tables.Micropost.MICROPOST;

    /**
     * The table <code>public.post_statistics</code>.
     */
    public static final PostStatistics POST_STATISTICS = micropost.data.tables.PostStatistics.POST_STATISTICS;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = micropost.data.tables.User.USER;
}
